package sn.ssi.togo.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "syg_bailleuretformation")
public class SygFormationBail implements java.io.Serializable  {
	private Integer id;
	private SygProformation formation;
	private SygBailleurs bailleur;
	private Long montant;
	private String num;
	private Date dateAccor;
	
	public SygFormationBail() {
		
	}

	public SygFormationBail(SygProformation formation, SygBailleurs bailleur,Long montant,String num,Date dateAccor) {
		
		this.formation = formation;
		this.bailleur = bailleur;
		this.montant=montant;
		this.num=num;
		this.dateAccor=dateAccor;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="id")
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="formation_id")
	public SygProformation getFormation() {
		return formation;
	}

	public void setFormation(SygProformation formation) {
		this.formation = formation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="bailleur_id")
	public SygBailleurs getBailleur() {
		return bailleur;
	}

	public void setBailleur(SygBailleurs bailleur) {
		this.bailleur = bailleur;
	}

	@Column(name="montant")
	public Long getMontant() {
		return montant;
	}
	public void setMontant(Long montant) {
		this.montant = montant;
	}

	@Column(name="numeroaccord")
	public String getNum() {
		return num;
	}

	
	public void setNum(String num) {
		this.num = num;
	}

	@Temporal(TemporalType.DATE)
	@Column(name ="dateaccord",  length = 10 )
	public Date getDateAccor() {
		return dateAccor;
	}

	public void setDateAccor(Date dateAccor) {
		this.dateAccor = dateAccor;
	}
	
	
}
