package sn.ssi.togo.model;
// Generated 23 janv. 2010 23:31:59 by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysAlerteprofil generated by hbm2java
 */
@Entity
@Table(name = "sys_alerteprofil")
public class SysAlerteprofil implements java.io.Serializable {

	private static final long serialVersionUID = 3986494343050164549L;
	private long id;
	private SysAlerte sysAlerte;
	private SysProfil sysProfil;

	public SysAlerteprofil() {
	}

	public SysAlerteprofil(long id, SysAlerte sysAlerte, SysProfil sysProfil) {
		this.id = id;
		this.sysAlerte = sysAlerte;
		this.sysProfil = sysProfil;
	}

	@Id
	@Column(name = "apf_id", unique = true, nullable = false)
	@GeneratedValue(strategy = IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alt_id", nullable = false)
	public SysAlerte getSysAlerte() {
		return this.sysAlerte;
	}

	public void setSysAlerte(SysAlerte sysAlerte) {
		this.sysAlerte = sysAlerte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pf_code", nullable = false)
	public SysProfil getSysProfil() {
		return this.sysProfil;
	}

	public void setSysProfil(SysProfil sysProfil) {
		this.sysProfil = sysProfil;
	}
}
