package sn.ssi.togo.model;
// Generated 19 avr. 2010 12:33:29 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PadAction generated by hbm2java
 */
@Entity
@Table(name = "sys_action")
public class SysAction implements java.io.Serializable {

	private String actCode;
	private SysFeature sysFeature;
	private short actJournal;
	private String actLibelle;
	private String actDesc;
	private String actApplicationstate;
	private String actImage;
	private Set<SysProfilAction> sysProfilActions = new HashSet<SysProfilAction>(
			0);

	public SysAction() {
	}

	public SysAction(String actCode, SysFeature sysFeature, short actJournal,
			String actLibelle, String actDesc, String actApplicationstate,
			String actImage, Set<SysProfilAction> sysProfilActions) {
		super();
		this.actCode = actCode;
		this.sysFeature = sysFeature;
		this.actJournal = actJournal;
		this.actLibelle = actLibelle;
		this.actDesc = actDesc;
		this.actApplicationstate = actApplicationstate;
		this.actImage = actImage;
		this.sysProfilActions = sysProfilActions;
	}

	@Id
	@Column(name = "act_code", unique = true, nullable = false, length = 50)
	public String getActCode() {
		return this.actCode;
	}

	public void setActCode(String actCode) {
		this.actCode = actCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fea_code", nullable = false)
	public SysFeature getSysFeature() {
		return this.sysFeature;
	}

	public void setSysFeature(SysFeature sysFeature) {
		this.sysFeature = sysFeature;
	}

	@Column(name = "act_journal", nullable = false)
	public short getActJournal() {
		return this.actJournal;
	}

	public void setActJournal(short actJournal) {
		this.actJournal = actJournal;
	}

	@Column(name = "act_libelle", nullable = false, length = 200)
	public String getActLibelle() {
		return this.actLibelle;
	}

	public void setActLibelle(String actLibelle) {
		this.actLibelle = actLibelle;
	}

	@Column(name = "act_desc", nullable = false, length = 32700)
	public String getActDesc() {
		return this.actDesc;
	}

	public void setActDesc(String actDesc) {
		this.actDesc = actDesc;
	}

	@Column(name = "act_applicationstate", nullable = false, length = 200)
	public String getActApplicationstate() {
		return this.actApplicationstate;
	}

	public void setActApplicationstate(String actApplicationstate) {
		this.actApplicationstate = actApplicationstate;
	}

	@Column(name = "act_image", nullable = false, length = 200)
	public String getActImage() {
		return this.actImage;
	}

	public void setActImage(String actImage) {
		this.actImage = actImage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysAction")
	public Set<SysProfilAction> getSysProfilActions() {
		return this.sysProfilActions;
	}

	public void setSysProfilActions(Set<SysProfilAction> sysProfilActions) {
		this.sysProfilActions = sysProfilActions;
	}

}
