package sn.ssi.togo.model;
// Generated 23 janv. 2010 23:31:59 by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

//import sn.ssi.sygmap.be.workflow.entity.SysState;

/**
 * PadAlerte generated by hbm2java
 */
@Entity
@Table(name = "sys_alerte")
public class SysAlerte implements java.io.Serializable {

	private long id;
	private String nom;
	private String desc;
	private Set<SysAlerteprofil> sysAlerteprofils = new HashSet<SysAlerteprofil>(
			0);
	private Set<SysUtilisateuralerte> sysUtilisateuralertes = new HashSet<SysUtilisateuralerte>(
			0);
	private String mode;
	private int delai;
	private String contenu;
	private int periode;
	private short notification;
	//private SysState sysState;

	public SysAlerte() {
	}

	public SysAlerte(long id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public SysAlerte(long id, String nom, String desc,
			Set<SysAlerteprofil> sysAlerteprofils,
			Set<SysUtilisateuralerte> sysUtilisateuralertes) {
		this.id = id;
		this.nom = nom;
		this.desc = desc;
		this.sysAlerteprofils = sysAlerteprofils;
		this.sysUtilisateuralertes = sysUtilisateuralertes;
	}

	@Column(name = "alt_notification", nullable = false)
	public short getNotification() {
		return notification;
	}

	public void setNotification(short notification) {
		this.notification = notification;
	}

	@Id
	@Column(name = "alt_id", unique = true, nullable = false)
	@GeneratedValue(strategy = IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "alt_nom", nullable = false, length = 200)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "alt_desc", length = 32700)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysAlerte")
	public Set<SysAlerteprofil> getSysAlerteprofils() {
		return this.sysAlerteprofils;
	}

	public void setSysAlerteprofils(Set<SysAlerteprofil> sysAlerteprofils) {
		this.sysAlerteprofils = sysAlerteprofils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysAlerte")
	public Set<SysUtilisateuralerte> getSysUtilisateuralertes() {
		return this.sysUtilisateuralertes;
	}

	public void setSysUtilisateuralertes(
			Set<SysUtilisateuralerte> sysUtilisateuralertes) {
		this.sysUtilisateuralertes = sysUtilisateuralertes;
	}

	@Column(name = "alt_mode", length = 200)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "alt_delai", nullable = false)
	public int getDelai() {
		return this.delai;
	}

	public void setDelai(int delai) {
		this.delai = delai;
	}

	@Column(name = "alt_contenu", length = 32700)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Column(name = "alt_periode", nullable = false)
	public int getPeriode() {
		return this.periode;
	}

	public void setPeriode(int periode) {
		this.periode = periode;
	}
//
//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "sta_code", nullable = false)
//	public SysState getSysState() {
//		return this.sysState;
//	}
//
//	public void setSysState(SysState sysState) {
//		this.sysState = sysState;
//	}

}
