package sn.ssi.togo.model;// Generated 19 avr. 2010 12:33:29 by Hibernate Tools 3.2.5.Beta

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PadFeature generated by hbm2java
 */
@Entity
@Table(name = "sys_feauture")
public class SysFeature implements Serializable {

	private String feaCode;
	private SysModule sysModule;
	private String feaLibelle;
	private String feaLibelle_en;
	private String feaLibelle_es;
	private String feaApplicationstate;
	private String feaDesc;
	private int feaSequence;
	private int feaDisplayable;

	private Set<SysAction> sysActions = new HashSet<SysAction>(0);

	public SysFeature() {
	}

	public SysFeature(String feaCode, SysModule module, String feaLibelle, String feaDesc, int feaSequence) {
		this.feaCode = feaCode;
		this.sysModule = module;
		this.feaLibelle = feaLibelle;
		this.feaDesc = feaDesc;
		this.feaSequence = feaSequence;
	}

	public SysFeature(String feaCode, SysModule module, String feaLibelle, String feaDesc, int feaSequence, Set<SysAction> sysActions) {
		this.feaCode = feaCode;
		this.sysModule = module;
		this.feaLibelle = feaLibelle;
		this.feaDesc = feaDesc;
		this.feaSequence = feaSequence;
		this.sysActions = sysActions;
	}

	@Id
	@Column(name = "fea_code", unique = true, nullable = false, length = 50)
	public String getFeaCode() {
		return this.feaCode;
	}

	public void setFeaCode(String feaCode) {
		this.feaCode = feaCode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mod_code", nullable = false)
	public SysModule getSysModule() {
		return this.sysModule;
	}

	public void setSysModule(SysModule module) {
		this.sysModule = module;
	}

	@Column(name = "fea_libelle", nullable = false, length = 200)
	public String getFeaLibelle() {
		return this.feaLibelle;
	}

	public void setFeaLibelle(String feaLibelle) {
		this.feaLibelle = feaLibelle;
	}

	@Column(name = "fea_libelleen", nullable = false, length = 200)
	public String getFeaLibelle_en() {
		return feaLibelle_en;
	}

	public void setFeaLibelle_en(String feaLibelleEn) {
		feaLibelle_en = feaLibelleEn;
	}

	@Column(name = "fea_libellees", nullable = false, length = 200)
	public String getFeaLibelle_es() {
		return feaLibelle_es;
	}

	public void setFeaLibelle_es(String feaLibelleEs) {
		feaLibelle_es = feaLibelleEs;
	}

	@Column(name = "fea_desc", nullable = false, length = 32700)
	public String getFeaDesc() {
		return this.feaDesc;
	}

	public void setFeaDesc(String feaDesc) {
		this.feaDesc = feaDesc;
	}

	@Column(name = "fea_sequence", nullable = false)
	public int getFeaSequence() {
		return this.feaSequence;
	}

	public void setFeaSequence(int feaSequence) {
		this.feaSequence = feaSequence;
	}

	@Column(name = "fea_displayable", nullable = false)
	public int getFeaDisplayable() {
		return this.feaDisplayable;
	}

	public void setFeaDisplayable(int feaDisplayable) {
		this.feaDisplayable = feaDisplayable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysFeature")
	public Set<SysAction> getSysActions() {
		return this.sysActions;
	}

	public void setSysActions(Set<SysAction> sysActions) {
		this.sysActions = sysActions;
	}

	@Column(name = "fea_applicationstate", nullable = false, length = 200)
	public String getFeaApplicationstate() {
		return feaApplicationstate;
	}

	public void setFeaApplicationstate(String feaApplicationstate) {
		this.feaApplicationstate = feaApplicationstate;
	}

}
