package sn.ssi.togo.model;
// Generated 26 mai 2010 22:14:26 by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PadJournal generated by hbm2java
 */
@Entity
@Table(name = "sys_journal")
public class SysJournal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7567767134137838219L;
	private Long jouId;
	private String actLibelle;
	private Date jouDate;
	private String jouDesc;
	private String usrLogin;

	public SysJournal() {
	}

	public SysJournal(String actLibelle, Date jouDate, String jouDesc,
			String usrLogin) {
		this.actLibelle = actLibelle;
		this.jouDate = jouDate;
		this.jouDesc = jouDesc;
		this.usrLogin = usrLogin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jou_id", unique = true, nullable = false)
	public Long getJouId() {
		return this.jouId;
	}

	public void setJouId(Long jouId) {
		this.jouId = jouId;
	}

	@Column(name = "act_libelle", nullable = false, length = 200)
	public String getActLibelle() {
		return this.actLibelle;
	}

	public void setActLibelle(String actLibelle) {
		this.actLibelle = actLibelle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "jou_date", nullable = false, length = 19)
	public Date getJouDate() {
		return this.jouDate;
	}

	public void setJouDate(Date jouDate) {
		this.jouDate = jouDate;
	}

	@Column(name = "jou_desc", nullable = false, length = 255)
	public String getJouDesc() {
		return this.jouDesc;
	}

	public void setJouDesc(String jouDesc) {
		this.jouDesc = jouDesc;
	}

	@Column(name = "usr_login", nullable = false, length = 200)
	public String getUsrLogin() {
		return this.usrLogin;
	}

	public void setUsrLogin(String usrLogin) {
		this.usrLogin = usrLogin;
	}

}
