package sn.ssi.togo.model;
// Generated 19 avr. 2010 12:33:29 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "sys_module")
public class SysModule implements java.io.Serializable {

	private String modCode;
	private String modLibelle_en;
	private String modLibelle_es;
	private String modLibelle;
	private String modDescription;
	private Integer modSequence;
	private Set<SysFeature> sysFeatures = new HashSet<SysFeature>(0);

	public SysModule() {
	}

	public SysModule(String modCode) {
		this.modCode = modCode;
	}

	public SysModule(String modCode, String modLibelle, String modDescription,
			Integer modSequence, Set<SysFeature> sysFeatures) {
		this.modCode = modCode;
		this.modLibelle = modLibelle;
		this.modDescription = modDescription;
		this.modSequence = modSequence;
		this.sysFeatures = sysFeatures;
	}

	@Id
	@Column(name = "mod_code", unique = true, nullable = false, length = 32)
	public String getModCode() {
		return this.modCode;
	}

	public void setModCode(String modCode) {
		this.modCode = modCode;
	}

	@Column(name = "mod_libelle", length = 64)
	public String getModLibelle() {
		return this.modLibelle;
	}

	public void setModLibelle(String modLibelle) {
		this.modLibelle = modLibelle;
	}

	@Column(name = "mod_libelleen", length = 64)
	public String getModLibelle_en() {
		return modLibelle_en;
	}

	public void setModLibelle_en(String modLibelleEn) {
		modLibelle_en = modLibelleEn;
	}

	@Column(name = "mod_libellees", length = 64)
	public String getModLibelle_es() {
		return modLibelle_es;
	}

	public void setModLibelle_es(String modLibelleEs) {
		modLibelle_es = modLibelleEs;
	}

	@Column(name = "mod_description", length = 1024)
	public String getModDescription() {
		return this.modDescription;
	}

	public void setModDescription(String modDescription) {
		this.modDescription = modDescription;
	}

	@Column(name = "mod_sequence")
	public Integer getModSequence() {
		return this.modSequence;
	}

	public void setModSequence(Integer modSequence) {
		this.modSequence = modSequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysModule")
	public Set<SysFeature> getSysFeatures() {
		return this.sysFeatures;
	}

	public void setSysFeatures(Set<SysFeature> sysFeatures) {
		this.sysFeatures = sysFeatures;
	}

}
