package sn.ssi.togo.model;
// Generated 12 f�vr. 2010 13:16:24 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PadParametresGeneraux generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sys_parametresgeneraux")
public class SysParametresGeneraux implements java.io.Serializable {

	

	private String code;
	private String libelle;
	private long valeur;
	
	//ADD Rama , 04-01-2013
	private Double taux;//Pour configuration des taux
	//private SygPays pays;

	public SysParametresGeneraux() {
	}
	public SysParametresGeneraux(String code, String libelle, long valeur) {
		this.code = code;
		this.libelle = libelle;
		this.valeur = valeur;
	}
	
	@Id
	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", nullable = false)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "valeur", nullable = false)
	public long getValeur() {
		return this.valeur;
	}

	public void setValeur(long valeur) {
		this.valeur = valeur;
	}
	
	
	//ADD Rama , 04-01-2013
	@Column(name = "taux")
	public Double getTaux() {
		return taux;
	}
	public void setTaux(Double taux) {
		this.taux = taux;
	}
	
//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "paysid")
//	public SygPays getPays() {
//		return pays;
//	}
//	public void setPays(SygPays pays) {
//		this.pays = pays;
//	}
	
	
	
	



	
	
}
