package sn.ssi.togo.model;
// Generated 3 d�c. 2009 10:24:05 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

//import sn.ssi.sygmap.be.workflow.entity.SysProfilarrowperm;
//import sn.ssi.sygmap.be.workflow.entity.SysRole;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "sys_profil")
public class SysProfil implements java.io.Serializable {

	private String pfCode,code;
	
	private String pfLibelle;
	private String pfDescription,type,codeprofil,user;
	
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<SysProfilAction> profilActions = new HashSet<SysProfilAction>(0);
	//private Set<SysRole> sysRoles = new HashSet<SysRole>(0);
	private Set<SysAlerteprofil> sysAlerteprofils = new HashSet<SysAlerteprofil>(
			0);
//	private Set<SysProfilarrowperm> sysProfilarrowperm = new HashSet<SysProfilarrowperm>(
//			0);
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProfil")
//	public Set<SysProfilarrowperm> getSysProfilarrowperm() {
//		return this.sysProfilarrowperm;
//	}
//
//	public void setSysProfilarrowperm(Set<SysProfilarrowperm> sysProfilarrowperm) {
//		this.sysProfilarrowperm = sysProfilarrowperm;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProfil")
	public Set<SysAlerteprofil> getSysAlerteprofils() {
		return this.sysAlerteprofils;
	}

	public void setSysAlerteprofils(Set<SysAlerteprofil> sysAlerteprofils) {
		this.sysAlerteprofils = sysAlerteprofils;
	}

	public SysProfil() {
	}

	public SysProfil(String code, String libelle) {
		this.pfCode = code;
		this.pfLibelle = libelle;
	}

	public SysProfil(String code, String libelle, String description,
			Set<SysModule> modules, Set<Utilisateur> utilisateurs
			//, Set<SysRole> sysRoles
	) {
		this.pfCode = code;
		this.pfLibelle = libelle;
		this.pfDescription = description;
		this.utilisateurs = utilisateurs;
	//	this.sysRoles = sysRoles;
	}

	@Id
	@Column(name = "pf_code", unique = true, nullable = false, length = 32)
	public String getPfCode() {
		return this.pfCode;
	}

	public void setPfCode(String code) {
		this.pfCode = code;
	}

	@Column(name = "pf_libelle", nullable = false, length = 128)
	public String getPfLibelle() {
		return this.pfLibelle;
	}

	public void setPfLibelle(String libelle) {
		this.pfLibelle = libelle;
	}

	@Column(name = "pf_description", length = 1024)
	public String getPfDescription() {
		return this.pfDescription;
	}

	public void setPfDescription(String description) {
		this.pfDescription = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProfil")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysProfil")
	public Set<SysProfilAction> getProfilActions() {
		return this.profilActions;
	}

	public void setProfilActions(Set<SysProfilAction> profilActions) {
		this.profilActions = profilActions;
	}

	/*
	 * @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	 * 
	 * @JoinTable(name = "PROFIL_ACTION", schema = "sygmap_gen", joinColumns = {
	 * 
	 * @JoinColumn(name = "pf_code", nullable = false, updatable = false) },
	 * inversejoincolumns = { @JoinColumn(name = "mac_code", nullable = false,
	 * updatable = false) }) public Set<ModuleAction> getModuleActions() {
	 * return this.moduleActions; }
	 * 
	 * public void setModuleActions(Set<ModuleAction> moduleActions) {
	 * this.moduleActions = moduleActions; }
	 */

//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "sysProfils")
//	public Set<SysRole> getSysRoles() {
//		return this.sysRoles;
//	}
//
//	public void setSysRoles(Set<SysRole> sysRoles) {
//		this.sysRoles = sysRoles;
//	}

	
	@Column(name = "pf_type", nullable = false, length = 50)
	public String getType() {
		return type;
	}
    public void setType(String type) {
		this.type = type;
	}
	
   
    @Column(name = "codepf",  length = 50)
    public String getCodeprofil() {
		return codeprofil;
	}
 	public void setCodeprofil(String codeprofil) {
		this.codeprofil = codeprofil;
	}

 	@Column(name = "usr",  length = 50)
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
 	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
