package sn.ssi.togo.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfilAction generated by hbm2java
 */
@Entity
@Table(name = "sys_profilaction")
public class SysProfilAction implements java.io.Serializable {

	private long pacId;
	private SysAction sysAction;
	private SysProfil sysProfil;
	private short allow;

	public SysProfilAction() {
	}

	public SysProfilAction(long pacId, SysAction sysAction, SysProfil sysProfil) {
		this.pacId = pacId;
		this.sysAction = sysAction;
		this.sysProfil = sysProfil;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "pac_id")
	public long getPacId() {
		return this.pacId;
	}

	public void setPacId(long pacId) {
		this.pacId = pacId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "act_code", nullable = false)
	public SysAction getSysAction() {
		return this.sysAction;
	}

	public void setSysAction(SysAction sysAction) {
		this.sysAction = sysAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pf_code", nullable = false)
	public SysProfil getSysProfil() {
		return this.sysProfil;
	}

	public void setSysProfil(SysProfil sysProfil) {
		this.sysProfil = sysProfil;
	}

	@Column(name = "allow", nullable = false)
	public short getAllow() {
		return this.allow;
	}

	public void setAllow(short allow) {
		this.allow = allow;
	}

}
