package sn.ssi.togo.model;
// Generated 3 d�c. 2009 10:24:05 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur")
public class Utilisateur implements java.io.Serializable {

	private Long id;
	private SysProfil sysProfil;
	private Set<SysUtilisateuralerte> sysUtilisateuralertes = new HashSet<SysUtilisateuralerte>(0);
	private String login;
	private String password;
	private String prenom;
	private String nom;
	private String mail,service,fonction,telephone,fax,adresse,type;
	private SygBureauxdcmp bureaux;
	private SygAutoriteContractante autorite;
	private SygService services;
	private Boolean actif;
	private Boolean chefService;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<SysUtilisateuralerte> getSysUtilisateuralertes() {
		return this.sysUtilisateuralertes;
	}

	public void setSysUtilisateuralertes(Set<SysUtilisateuralerte> sysUtilisateuralertes) {
		this.sysUtilisateuralertes = sysUtilisateuralertes;
	}

	public Utilisateur() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "usr_id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pf_code")
	public SysProfil getSysProfil() {
		return this.sysProfil;
	}

	public void setSysProfil(SysProfil sysProfil) {
		this.sysProfil = sysProfil;
	}

	@Column(name = "usr_login", length = 200)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "usr_password", length = 200)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "usr_prenom", length = 200)
	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "usr_nom", length = 200)
	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "usr_mail", length = 200)
	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	
	@Column(name = "usr_service")
	public String getService() {
		return service;
	}

	public void setService(String service) {
		this.service = service;
	}

	
	@Column(name = "usr_fonction")
	public String getFonction() {
		return fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	
	@Column(name = "usr_tel")
	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	
	@Column(name = "usr_fax")
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	
	@Column(name = "usr_adresse")
	public String getAdresse() {
		return adresse;
	}
    public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

    
    @Column(name = "usr_type")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "br_id")
	public SygBureauxdcmp getBureaux() {
		return bureaux;
	}

	public void setBureaux(SygBureauxdcmp bureaux) {
		this.bureaux = bureaux;
	}

	
	@Column(name = "usr_actif")
	public Boolean getActif() {
		return actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "autorite")
	public SygAutoriteContractante getAutorite() {
		return autorite;
	}

	public void setAutorite(SygAutoriteContractante autorite) {
		this.autorite = autorite;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service")
	public SygService getServices() {
		return services;
	}

	public void setServices(SygService services) {
		this.services = services;
	}
	
	@Column(name = "usr_chef")
	public Boolean getChefService() {
		return chefService;
	}

	public void setChefService(Boolean chefService) {
		this.chefService = chefService;
	}
	
}
